### ISSUE TITLE
Behaviour of the RoundUp Function

### ISSUE THREAD

**Issue by lukasgartmair** [lukasgartmair/OpenVDB_TestSuite#1]
The helper function round up in order to get the ions voxel index from its coordinates shows strange behaviour and it has to be discussed whether this is suitable for this purpose.
Maybe an alternative would be better.

**Comment by 0joshuaolson1** [comment]
Is this something that upstream's test suite could benefit from?

**Comment by lukasgartmair** [comment]
Hey Joshua, what exactly do you mean with upstream's test suite?

**Comment by 0joshuaolson1** [comment]
Wow, my bad. I didn't make a new issue.

**Comment by lukasgartmair** [comment]
completely replaced with a more sophisticated contribution transfer function, which can be found in the CTF repository.
